"""v3_add_soft_delete_tokens_audit_encryption

Revision ID: dd6044122d27
Revises: 882765148640
Create Date: 2026-04-30 15:26:22.570514
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'dd6044122d27'
down_revision: Union[str, None] = '882765148640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('apps', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('apps', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('documents', sa.Column('s3_key', sa.String(length=512), nullable=False))
    op.add_column('documents', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.alter_column('documents', 'file_size',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_column('documents', 'storage_path')
    op.add_column('index_jobs', sa.Column('cancel_reason', sa.String(length=256), nullable=True))
    op.add_column('systems', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.alter_column('systems', 'gitlab_token',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.add_column('users', sa.Column('status', sa.String(length=16), nullable=False))
    op.add_column('users', sa.Column('system_quota', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('login_fail_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'login_fail_count')
    op.drop_column('users', 'system_quota')
    op.drop_column('users', 'status')
    op.alter_column('systems', 'gitlab_token',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               existing_nullable=True)
    op.drop_column('systems', 'deleted')
    op.drop_column('index_jobs', 'cancel_reason')
    op.add_column('documents', sa.Column('storage_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512), nullable=False))
    op.alter_column('documents', 'file_size',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('documents', 'deleted')
    op.drop_column('documents', 's3_key')
    op.drop_column('apps', 'deleted')
    op.drop_column('apps', 'version')
    op.drop_table('api_tokens')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
